apiVersion: v1
kind: Service
metadata:
  labels:
    app: personal-blog
  name: personal-blog
  namespace: personal-blog
spec:
  type: LoadBalabcer
  ports:
    - name: "personal-blog"
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: personal-blog
